### ISSUE TITLE
[BUG] taiga-events crashed.

### ISSUE THREAD

**Issue by jeffery9** [taigaio/taiga-docker#2]
**Describe the bug**

service taiga-events crashed, and reported 
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start:production'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v12.20.1
4 verbose config Skipping project config: /taiga-events/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart:production', 'start:production', 'poststart:production' ]
6 info lifecycle taigaio-events@6.0.2~prestart:production: taigaio-events@6.0.2
7 info lifecycle taigaio-events@6.0.2~start:production: taigaio-events@6.0.2
8 verbose lifecycle taigaio-events@6.0.2~start:production: unsafe-perm in lifecycle true
9 verbose lifecycle taigaio-events@6.0.2~start:production: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/taiga-events/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle taigaio-events@6.0.2~start:production: CWD: /taiga-events
11 silly lifecycle taigaio-events@6.0.2~start:production: Args: [ '-c', 'NODE_ENV=production node ./src/index.js' ]
12 silly lifecycle taigaio-events@6.0.2~start:production: Returned: code: 1  signal: null
13 info lifecycle taigaio-events@6.0.2~start:production: Failed to exec start:production script
14 verbose stack Error: taigaio-events@6.0.2 start:production: `NODE_ENV=production node ./src/index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:314:20)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:314:20)
14 verbose stack     at maybeClose (internal/child_process.js:1022:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
15 verbose pkgid taigaio-events@6.0.2
16 verbose cwd /taiga-events
17 verbose Linux 4.4.0-130-generic
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:production"
19 verbose node v12.20.1
20 verbose npm  v6.14.10
21 error code ELIFECYCLE
22 error errno 1
23 error taigaio-events@6.0.2 start:production: `NODE_ENV=production node ./src/index.js`
23 error Exit status 1
24 error Failed at the taigaio-events@6.0.2 start:production script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```
**How can we reproduce the behavior**

**Workarounds**

**Screenshots**

**Taiga environment**

taiga 6.0.4

**Desktop (please complete the following information):**
 - **OS:** 
 - **Browser:** 
 - **Version:** 

**Additional context**

**Comment by NatachaMenjibar** [comment]
Hi, @jeffery9 
Could you give us a some info about how to reproduce this behaviour?

**Comment by jeffery9** [comment]
the steps to reproduce this bug

1. clone taiga-docker repository ` git clone https://github.com/taigaio/taiga-docker.git`
2. `cd taiga-docker` and `git checkout 6.0.4`
3. modify `docker-compose.yml` , change the following settings according your envs

> TAIGA_SECRET_KEY
> TAIGA_SITES_DOMAIN
> TAIGA_URL
> TAIGA_WEBSOCKETS_URL
> SECRET_KEY

4. startup docker `launch-taiga.sh`
5.  taiga_events is running, but it should crashed in randomly 

the docker version is 
```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Fri Dec 18 12:33:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:53:57 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by nemonik** [comment]
Did you add `EVENTS_PUSH_BACKEND_URL` and `CELERY_BROKER_URL`?  I found doing so got me the same error.
