### ISSUE TITLE
Problems initiating superuser 

### ISSUE THREAD

**Issue by andresazp** [taigaio/taiga-docker#30]
**Describe the bug**
When trying to create a superuser, and probably other manage.py actions, after configuring the host and domian it returns a DB error: `django.db.utils.OperationalError: FATAL:  password authentication failed for user "taiga"`

```

$ ./taiga-manage.sh createsuperuser
Creating taiga-docker_taiga-manage_run ... done
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "taiga"
```

Could it be that taiga-docker_taiga-manage_run is not finding the database like the other containers?

**Comment by yamila-moreno** [comment]
Hi @andresazp it seems that you changed the connection data for the database but you didn't change the connection data for the backend (or vice-versa). Could you check if you have both configurations (taiga-back and taiga-db) with the same information?

**Comment by andresazp** [comment]
@yamila-moreno Indeed there was something else awry. Not a bug, sorry

**Comment by yamila-moreno** [comment]
cool you figured it out! Then I'm closing the issue.

**Comment by AnasGhrab** [comment]
I have the same problem, I have repeated the operation multiple times : 
```
anas@lsd:~$ git clone https://github.com/taigaio/taiga-docker
Cloning into 'taiga-docker'...
remote: Enumerating objects: 104, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 267 (delta 51), reused 63 (delta 27), pack-reused 163
Receiving objects: 100% (267/267), 516.12 KiB | 815.00 KiB/s, done.
Resolving deltas: 100% (132/132), done.
anas@lsd:~$ cd taiga-docker/
anas@lsd:~/taiga-docker$ git checkout stable
Branch stable set up to track remote branch stable from origin.
Switched to a new branch 'stable'
anas@lsd:~/taiga-docker$ ls
AUTHORS.rst   CONTRIBUTING.md  LICENSE    VERSION.md                docker-compose.penpot.yml  imgs           launch-taiga.sh  taiga-manage.sh
CHANGELOG.md  DCOLICENSE       README.md  docker-compose-inits.yml  docker-compose.yml         launch-all.sh  taiga-gateway
anas@lsd:~/taiga-docker$ sudo ./launch-taiga.sh 
+ exec docker-compose -f docker-compose.yml up -d
Creating network "taiga-docker_taiga" with the default driver
Pulling taiga-db (postgres:12.3)...
12.3: Pulling from library/postgres
bf5952930446: Pull complete
9577476abb00: Pull complete
2bd105512d5c: Pull complete
b1cd21c26e81: Pull complete
34a7c86cf8fc: Pull complete
274e7b0c38d5: Pull complete
3e831b350d37: Pull complete
38fa0d496534: Pull complete
31a8349609a4: Pull complete
14e4c2a4b7b7: Pull complete
964acfa02beb: Pull complete
31b1f20dffc0: Pull complete
14771c2930e9: Pull complete
2f30edd0ce8a: Pull complete
Digest: sha256:a06e6e6e519b7a329c419f8221edec66cfc45511e8b80e262c12103ba745cf19
Status: Downloaded newer image for postgres:12.3
Pulling taiga-async-rabbitmq (rabbitmq:3-management-alpine)...
3-management-alpine: Pulling from library/rabbitmq
4c0d98bf9879: Pull complete
51cff74546c6: Pull complete
44d9385a724f: Pull complete
fbbd195a5109: Pull complete
87105e64f72f: Pull complete
8ba6b4c4377f: Pull complete
718d9257f99a: Pull complete
5f79429b6ca2: Pull complete
2474d92a09ec: Pull complete
3ceaae2f21c1: Pull complete
2e7d31a914e6: Pull complete
Digest: sha256:c1db4e4ccfbfdbc23b4a49cf2eeb336cc0fd2f5e5e005021d44eefa172d86720
Status: Downloaded newer image for rabbitmq:3-management-alpine
Pulling taiga-front (taigaio/taiga-front:latest)...
latest: Pulling from taigaio/taiga-front
df20fa9351a1: Pull complete
3db268b1fe8f: Pull complete
f682f0660e7a: Pull complete
7eb0e8838bc0: Pull complete
e8bf1226cc17: Pull complete
9f841bc6f8f2: Pull complete
896f171ecdf2: Pull complete
210c4d69b3f0: Pull complete
45a9736b0005: Pull complete
Digest: sha256:8472d60a9647f31fc426b34f39ab77b53a5b5dde9a6c92e6f5c3229aa459b658
Status: Downloaded newer image for taigaio/taiga-front:latest
Pulling taiga-events (taigaio/taiga-events:latest)...
latest: Pulling from taigaio/taiga-events
0a6724ff3fcd: Pull complete
5fd2bdfdbf4b: Pull complete
80b224d472a8: Pull complete
e21405c347ae: Pull complete
f25bc5b23591: Pull complete
d7017a5d2dad: Pull complete
Digest: sha256:bc90131f768beaec75fd5198c6b45da7faa9cbb83a17c15f3b93153e0ffa7562
Status: Downloaded newer image for taigaio/taiga-events:latest
Pulling taiga-back (taigaio/taiga-back:latest)...
latest: Pulling from taigaio/taiga-back
d121f8d1c412: Pull complete
ca572574cc82: Pull complete
2bec6349c99d: Pull complete
087ac0b72728: Pull complete
6ca52d7c92b3: Pull complete
666633871952: Pull complete
28beef6da9b9: Pull complete
9b38a5f75327: Pull complete
Digest: sha256:1d3961c993ff9d692d8ab587fa56dc533101c94b34d60c560b0997e1af8c0bf9
Status: Downloaded newer image for taigaio/taiga-back:latest
Pulling taiga-protected (taigaio/taiga-protected:latest)...
latest: Pulling from taigaio/taiga-protected
a076a628af6f: Pull complete
a36ca90be64c: Pull complete
420e4b6220ed: Pull complete
772a2b254861: Pull complete
cdd040608d7b: Pull complete
d1766f058f3d: Pull complete
e3d8fcf3659b: Pull complete
b6b0faa003d1: Pull complete
Digest: sha256:fb01ee391d903bd0569ccf7c0f881f3890418e17a3f04625bbaf89639d0e5cd7
Status: Downloaded newer image for taigaio/taiga-protected:latest
Pulling taiga-gateway (nginx:1.19-alpine)...
1.19-alpine: Pulling from library/nginx
801bfaa63ef2: Pull complete
b1242e25d284: Pull complete
7453d3e6b909: Pull complete
07ce7418c4f8: Pull complete
e295e0624aa3: Pull complete
Digest: sha256:c2ce58e024275728b00a554ac25628af25c54782865b3487b11c21cafb7fabda
Status: Downloaded newer image for nginx:1.19-alpine
Creating taiga-docker_taiga-protected_1       ... done
Creating taiga-docker_taiga-events-rabbitmq_1 ... done
Creating taiga-docker_taiga-front_1           ... done
Creating taiga-docker_taiga-db_1              ... done
Creating taiga-docker_taiga-async-rabbitmq_1  ... done
Creating taiga-docker_taiga-events_1          ... done
Creating taiga-docker_taiga-back_1            ... done
Creating taiga-docker_taiga-async_1           ... done
Creating taiga-docker_taiga-gateway_1         ... done
anas@lsd:~/taiga-docker$ sudo ./taiga-manage.sh createsuperuser
+ exec docker-compose -f docker-compose.yml -f docker-compose-inits.yml run --rm taiga-manage createsuperuser
Starting taiga-docker_taiga-db_1 ... done
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "taiga"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 61, in execute
    return super().execute(*args, **options)
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 363, in execute
    self.check_migrations()
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 453, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "taiga"

```

**Comment by yamila-moreno** [comment]
Hi @AnasGhrab did you wait a minute after all the services were "Done"? can you `launch` taiga, then wait for a minute and then try the createsuperuser? I'm reproducing the behaviour when I don't wait enough.

We have plans to improve the dependency system, but right now we're relying on compose's `depends on` and it's not super accurate (it's a known issue in fact).

Please, let us know if it worked.

**Comment by AnasGhrab** [comment]
It's seem that I had a conflict with another postgresql image, with another version, which was used by another instance. It's ok now..

**Comment by Mbd06b** [comment]
I'm running into this problem.  Does any anyone have any suggestions to debug it?  

I don't see any other postgresql images open... when I check ` docker container ls `
This is using everything from scratch @tag 6.5.0 and only minimal updates to the compose files customizing my instance URLs https://docs.taiga.io/setup-production.html  


`~/taiga-docker$ ./taiga-manage.sh createsuperuser
+ exec docker-compose -f docker-compose.yml -f docker-compose-inits.yml run --rm taiga-manage createsuperuser
Creating taiga-docker_taiga-manage_run ... done
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "taiga"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 61, in execute
    return super().execute(*args, **options)
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 363, in execute
    self.check_migrations()
  File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 453, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "taiga"`

**Comment by Mbd06b** [comment]
I solved it out..

if your postgres volume already has data in it, (from a different install attempt) then it won't initialize properly.
https://github.com/docker-library/postgres/issues/773#issuecomment-710144766

I checked that by finding the postgres container and logging into the container... and looking at the contents of this directory... /var/lib/postgresql/data and found a bunch of stuff...
See: https://www.ibm.com/docs/en/workload-automation/9.5.0?topic=compose-accessing-docker-containers

from docker-compose.yml:
volumes:
- taiga-db-data:/var/lib/postgresql/data

In order to re-initialize postgres with the user and password specified, I cleared out the containers AND any volumes.
https://stackoverflow.com/a/58573823

You can clear that out with this...
docker-compose down --rmi all --volumes

Then trying again.
That fixed my issue.
