### ISSUE TITLE
taiga_contrib_ldap_auth contrib

### ISSUE THREAD

**Issue by hormiai76** [taigaio/taiga-docker#42]
I'm using taiga 5 in a virtual machine and I would like to move to taiga-docker but I cannot find a way to configure the **taiga_contrib_ldap_auth**

I added the confogurations needed in the config.py and uncommented the line in the docker-compose file but when I run "docker-compose up" it gives an error.

```
taiga-back               | Executing pending migrations
taiga-back               | Traceback (most recent call last):
taiga-back               |   File "manage.py", line 27, in <module>
taiga-back               |     execute_from_command_line(sys.argv)
taiga-back               |   File "/opt/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
taiga-back               |     utility.execute()
taiga-back               |   File "/opt/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
taiga-back               |     django.setup()
taiga-back               |   File "/opt/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
taiga-back               |     apps.populate(settings.INSTALLED_APPS)
taiga-back               |   File "/opt/venv/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
taiga-back               |     app_config = AppConfig.create(entry)
taiga-back               |   File "/opt/venv/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
taiga-back               |     module = import_module(entry)
taiga-back               |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
taiga-back               |     return _bootstrap._gcd_import(name[level:], package, level)
taiga-back               |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
taiga-back               |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
taiga-back               |   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
taiga-back               | ModuleNotFoundError: No module named 'taiga_contrib_ldap_auth'
```

Could you add a small guide to help us to install new contribs?

Regards,

Alberto

**Comment by yamila-moreno** [comment]
Hi @hormiai76 !

To install ldap plugin, you should take the official Dockerfiles and add the installation of this plugin (pip install or svn export when needed) and build them.

Cheers!
