### ISSUE TITLE
Sending mails from localhost

### ISSUE THREAD

**Issue by AnasGhrab** [taigaio/taiga-docker#52]
I can't send emails using postfix installed on the same host, even if I have ```inet_interfaces = all```
I have uncommented in the docker-compose.yml the variables related to mail, ```EMAIL_BACKEND```

Is setting the EMAIL_HOST necessary when it's the same host ? Should that variable be ```localhost``` and the default port 25 ?

Thanks.

```
taiga-back_1             | ERROR:2021-02-24 16:16:20,632: Internal Server Error: /api/v1/memberships/11/resend_invitation
taiga-back_1             | Traceback (most recent call last):
taiga-back_1             |   File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
taiga-back_1             |     response = get_response(request)
taiga-back_1             |   File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
taiga-back_1             |     response = self.process_exception_by_middleware(e, request)
taiga-back_1             |   File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
taiga-back_1             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
taiga-back_1             |   File "/taiga-back/taiga/base/api/viewsets.py", line 104, in view
taiga-back_1             |     return self.dispatch(request, *args, **kwargs)
taiga-back_1             |   File "/opt/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
taiga-back_1             |     return view_func(*args, **kwargs)
taiga-back_1             |   File "/taiga-back/taiga/base/api/views.py", line 458, in dispatch
taiga-back_1             |     response = self.handle_exception(exc)
taiga-back_1             |   File "/taiga-back/taiga/base/api/views.py", line 456, in dispatch
taiga-back_1             |     response = handler(request, *args, **kwargs)
taiga-back_1             |   File "/taiga-back/taiga/projects/api.py", line 1078, in resend_invitation
taiga-back_1             |     services.send_invitation(invitation=invitation)
taiga-back_1             |   File "/taiga-back/taiga/projects/services/invitations.py", line 32, in send_invitation
taiga-back_1             |     email.send()
taiga-back_1             |   File "/opt/venv/lib/python3.7/site-packages/django/core/mail/message.py", line 306, in send
taiga-back_1             |     return self.get_connection(fail_silently).send_messages([self])
taiga-back_1             |   File "/opt/venv/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
taiga-back_1             |     new_conn_created = self.open()
taiga-back_1             |   File "/opt/venv/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 63, in open
taiga-back_1             |     self.connection = self.connection_class(self.host, self.port, **connection_params)
taiga-back_1             |   File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
taiga-back_1             |     (code, msg) = self.connect(host, port)
taiga-back_1             |   File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
taiga-back_1             |     self.sock = self._get_socket(host, port, self.timeout)
taiga-back_1             |   File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
taiga-back_1             |     self.source_address)
taiga-back_1             |   File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
taiga-back_1             |     raise err
taiga-back_1             |   File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
taiga-back_1             |     sock.connect(sa)
taiga-back_1             | OSError: [Errno 99] Cannot assign requested address
```

**Comment by skepticalwaves** [comment]
I couldn't get external host email sending working either.

**Comment by yomguy** [comment]
Hi @AnasGhrab :)

You should not use `localhost` which refers to the container itself in its own context. Try to use the IP of the interface of the host or the domain assigned to it. Of course, in this case, the email server of the host should be configured to respond to it.

**Comment by yamila-moreno** [comment]
Hi there. Thanks @yomguy you're totally right.

@AnasGhrab I see two options:

- (following your initial setup) run postfix in your host listening in all interfaces, and configure your email to the ip of the docker bridge (which may vay). **We strongly recommend avoiding this**. Nonetheless, it's not a matter of Taiga, but a matter of docker and communications with the host.

- (recommended) the other option that probably would be better for this situation is to add a `taiga-postfix` service in the `docker-compose.yml` (in the same network as the rest of taiga), and make your backend to point to this postfix.

Cheers!
