### ISSUE TITLE
Event and async containers crash

### ISSUE THREAD

**Issue by saul-avikar** [taigaio/taiga-docker#73]
I have setup taiga-docker as per the [documentation](https://taigaio.github.io/taiga-doc/dist/setup-production.html) but although I can see the interface and login, I cannot create projects and the web console keeps outputting websocket errors.

### Configuration
My nginx config looks exactly the same as the documentation's with the exception of listening on port 443 and a different server_name. My **docker-compose** is setup for https (and wss) instead of http.

### Observations
`docker container ls -a` shows that the **taiga-docker_taiga-async_1** container had exited immediately and the **taiga-docker_taiga-events_1** container exited 30s later. The **taiga-docker_taiga-gateway_1** logs show that GET /events failed because Host is unreachable.

Visiting /events returns a 502 in the browser (it did show "upgrade required" briefly but I cannot reproduce that anymore).

### Versions
Docker version 20.10.5, build 55c4c88
docker-compose version 1.29.0, build 07737305

### Possible related issues
- https://github.com/taigaio/taiga-docker/issues/65
- https://github.com/taigaio/taiga-docker/issues/18
- https://github.com/taigaio/taiga-docker/issues/58

### taiga-docker_taiga-async_1
Note celery is disabled in **docker-compose-inits.yml**
CELERY_ENABLED: "False"
```
Give permission to taiga:taiga
Starting Celery...
Traceback (most recent call last):
  File "/opt/venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.7/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/opt/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/opt/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/venv/lib/python3.7/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/opt/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/opt/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/opt/venv/lib/python3.7/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/opt/venv/lib/python3.7/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/celery/worker/worker.py", line 101, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/opt/venv/lib/python3.7/site-packages/celery/worker/worker.py", line 122, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/opt/venv/lib/python3.7/site-packages/celery/app/base.py", line 776, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/celery/app/base.py", line 852, in _connection
    'broker_connection_timeout', connect_timeout
  File "/opt/venv/lib/python3.7/site-packages/kombu/connection.py", line 188, in __init__
    transport = transport or urlparse(hostname).scheme
  File "/usr/local/lib/python3.7/urllib/parse.py", line 368, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 459, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```
### taiga-docker_taiga-events_1
```
Starting Taiga events

> taigaio-events@6.0.2 start:production /taiga-events
> NODE_ENV=production node ./src/index.js

{"message":"WS server is started","level":"info","service":"taiga-events","timestamp":"2021-04-14 01:55:18"}
{"message":"Liveness / Readiness server was started in http://localhost:3023/healthz","level":"info","service":"taiga-events","timestamp":"2021-04-14 01:55:18"}
{"message":"ws-connection-open: 74ffd1d3-d1b4-470e-ab39-6e81f42bd0e5","level":"info","service":"taiga-events","timestamp":"2021-04-14 01:55:44"}
{"message":"auth: {\"cmd\":\"auth\",\"data\":{\"token\":\"<REDACTED>\",\"sessionId\":\"<REDACTED>\"}}","level":"info","service":"taiga-events","timestamp":"2021-04-14 01:55:44"}
{"message":"subscribe: {\"cmd\":\"subscribe\",\"routing_key\":\"notifications\"}","level":"info","service":"taiga-events","timestamp":"2021-04-14 01:55:44"}
{"message":"subscribe: {\"cmd\":\"subscribe\",\"routing_key\":\"web_notifications.5\"}","level":"info","service":"taiga-events","timestamp":"2021-04-14 01:55:44"}
{"message":"Unhandled Rejection: \"Error: getaddrinfo ENOTFOUND taiga:[.cas9wpsb8u:klpcsgn)\"","level":"warn","service":"taiga-events","timestamp":"2021-04-14 01:55:44"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taigaio-events@6.0.2 start:production: `NODE_ENV=production node ./src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taigaio-events@6.0.2 start:production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /taiga-events/.npm/_logs/2021-04-14T01_55_44_564Z-debug.log
```

**Comment by yamila-moreno** [comment]
Hi @saul-avikar please, share your `docker-compose.yml` **with the credentials redacted** so we can figure what happened.

**Comment by saul-avikar** [comment]
### docker-compose.yml
```
version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: <REDACTED>
  POSTGRES_PASSWORD: "<REDACTED>"
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "<REDACTED>"
  TAIGA_SITES_DOMAIN: "taiga.<REDACTED>"
  TAIGA_SITES_SCHEME: "https"
  # Email settings. Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "no-reply@taiga.<REDACTED>"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "False"
  EMAIL_HOST: "<REDACTED>"
  EMAIL_PORT: 587
  EMAIL_HOST_USER: "<REDACTED>"
  EMAIL_HOST_PASSWORD: "<REDACTED>"
  # Rabbitmq settings
  # Should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER: <REDACTED>
  RABBITMQ_PASS: "<REDACTED>"
  # Telemetry settings
  ENABLE_TELEMETRY: "False"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py


services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: <REDACTED>
      POSTGRES_PASSWORD: "<REDACTED>"
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: <REDACTED>
      RABBITMQ_DEFAULT_PASS: "<REDACTED>"
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "https://taiga.<REDACTED>"
      TAIGA_WEBSOCKETS_URL: "wss://taiga.<REDACTED>"
    networks:
      - taiga
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: <REDACTED>
      RABBITMQ_PASS: "<REDACTED>"
      TAIGA_SECRET_KEY: "<REDACTED>"
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: <REDACTED>
      RABBITMQ_DEFAULT_PASS: "<REDACTED>"
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: 360
      SECRET_KEY: "<REDACTED>"
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:
```
Note: `TAIGA_SITES_DOMAIN`, `TAIGA_URL` and `TAIGA_WEBSOCKETS_URL` are the same domain.

**Comment by yamila-moreno** [comment]
Hi @saul-avikar the docker-compose.yml seems ok.

Let's discard one scenario: there is a known issue related to services dependencies. The `events` container is launched when the `rabbit` container is already running, but the rabbit service is not 100% ready yet. We plan to add better dependencies to this case.

So the test if this is your case:
- launch docker-compose up -d
- check if every service is up&running
- if async or events (those which consume rabbitmq) give an error, please, run again `docker-compose up -d` (after a few seconds, to be sure that the rabbitmqs are really ready)

Cheers!

**Comment by saul-avikar** [comment]
Thanks @yamila-moreno,

I have finally figured it out - the passwords contained symbols that must have not been sanitized, simply changing them to alpha-numeric sorted it out. Would be nice to get more specific errors if the **docker-compose.yml** has any problems.

My passwords contained the following symbols for reference `()<>[{?&!,+:#^@./%`

**Comment by yamila-moreno** [comment]
Thanks @saul-avikar we'll take a look at it!

**Comment by DanInSpace104** [comment]
> * launch docker-compose up -d
> * check if every service is up&running
> * if async or events (those which consume rabbitmq) give an error, please, run again `docker-compose up -d` (after a few seconds, to be sure that the rabbitmqs are really ready)

Thank you for this solution! Is it in documentation? I couldn't find it :upside_down_face:
