### ISSUE TITLE
[BUG] Problems initiating postgres db user. FATAL: password authentication failed for user "taiga"

### ISSUE THREAD

**Issue by Mbd06b** [taigaio/taiga-docker#81]
I'm running into this problem, and stuck.  I know it's the POSTGRES_DB user unable to authenticate when I try to create the superuser step.   
`/taiga-manage.sh createsuperuser`   Does any anyone have any suggestions to debug it?

I don't see any other postgresql images open... when I check docker container ls
This is using everything from scratch @tag 6.5.0 and only minimal updates to the compose files customizing my instance URLs https://docs.taiga.io/setup-production.html 

Some others have experienced this issue here... https://github.com/taigaio/taiga-docker/issues/30 but they didn't expand upon how they got it working. 
  
I imagine that there's a disconnect here between what password is being created in the container, and what the script is trying to use to create the super user when you` docker-compose up -d.`   so something else is wrong here. 

`~/taiga-docker$ ./taiga-manage.sh createsuperuser

exec docker-compose -f docker-compose.yml -f docker-compose-inits.yml run --rm taiga-manage createsuperuser
Creating taiga-docker_taiga-manage_run ... done
Traceback (most recent call last):
File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
self.connect()
File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
self.connection = self.get_new_connection(conn_params)
File "/opt/venv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
connection = Database.connect(**conn_params)
File "/opt/venv/lib/python3.7/site-packages/psycopg2/init.py", line 127, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL: password authentication failed for user "taiga"
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "manage.py", line 17, in
execute_from_command_line(sys.argv)
File "/opt/venv/lib/python3.7/site-packages/django/core/management/init.py", line 381, in execute_from_command_line
utility.execute()
File "/opt/venv/lib/python3.7/site-packages/django/core/management/init.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
self.execute(*args, **cmd_options)
File "/opt/venv/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 61, in execute
return super().execute(*args, **options)
File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 363, in execute
self.check_migrations()
File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 453, in check_migrations
executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in init
self.loader = MigrationLoader(self.connection)
File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in init
self.build_graph()
File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
self.applied_migrations = recorder.applied_migrations()
File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
if self.has_table():
File "/opt/venv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
return self._cursor()
File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
self.ensure_connection()
File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
self.connect()
File "/opt/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in exit
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
self.connect()
File "/opt/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
self.connection = self.get_new_connection(conn_params)
File "/opt/venv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
connection = Database.connect(**conn_params)
File "/opt/venv/lib/python3.7/site-packages/psycopg2/init.py", line 127, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL: password authentication failed for user "taiga"`

**Comment by Mbd06b** [comment]
I solved it out.. 

if your postgres volume already has data in it, (from a different install attempt)  then it won't initialize properly. 
https://github.com/docker-library/postgres/issues/773#issuecomment-710144766 

I checked that  by finding the postgres container and logging into the container...  and looking at the contents of this directory... /var/lib/postgresql/data  and found a bunch of stuff...
See: https://www.ibm.com/docs/en/workload-automation/9.5.0?topic=compose-accessing-docker-containers 

from docker-compose.yml: 
volumes:
      - taiga-db-data:/var/lib/postgresql/data

In order to re-initialize postgres with the user and password specified, I cleared out the containers AND any volumes. 
https://stackoverflow.com/a/58573823 

You can clear that out with this...  
`docker-compose down --rmi all --volumes`

Then trying again. 
That fixed my issue.
